### ISSUE TITLE
Readme requirements not clear

### ISSUE THREAD

**Issue by viig99** [hashedin/squealy#157]
1) Readme doesn't mention cases where this tool might be useful.
2) Doesnt mention what all data sources it supports, mysql, pgsql, cassandra, hive, hbase etc ?
3) How can we plug in file based data source etc ?
4) can custom dashboard charts be supported through d3, or new features can be built ?

**Comment by swapnil95** [comment]
Please look into the phase-2 branch for the latest readme. We will be moving it to master pretty soon

**Comment by viig99** [comment]
Took a look at the phase-2 branch readme, same concerns above,
is there support only for mysql, pgsql ? 
Also is there ability to parse big streaming data & have runtime visualization of parameters like kibana, graylog?

**Comment by swapnil95** [comment]
Right now we support relational databases. Thanks for pointing that out

**Comment by swapnil95** [comment]
Closing this issue as we have updated the readme to make the requirements clear

**Comment by swapnil95** [comment]
Closing this issue as we have updated the readme to make the requirements clear
