### ISSUE TITLE
frontend not loading

### ISSUE THREAD

**Issue by asurancetturix** [hashedin/squealy#224]
When loading the react aplication we get an error on loadInitialCharts. It is receiving an html page instead of an (assume) array of the charts.
`Uncaught TypeError: response.map is not a function         AuthoringInterfaceContainer.js:209`

**Comment by swapnil95** [comment]
Can you try logging in first on localhost:8000 first and then try running the frontend

Looks like the login redirection is breaking from localhost:3000. Its working on production though

**Comment by asurancetturix** [comment]
worked!
thank you @swapnil95
