### ISSUE TITLE
Specifying Python supported versions

### ISSUE THREAD

**Issue by mcarrilloco** [hashedin/squealy#226]
Hi,

Thanks for sharing this useful project. I am currently going through the effort of "dockerizing" the code and it was hard for me to figure out what versions of python the project was build for and tested on. Through the process I realized that python 3 is not an option given the dependency `MySQL-python` which is not compatible (maybe it is worth looking into changing for `mysqlclient` which is a fork of the former one and python 3 compatible). Anyway, I think it is worth mentioning in the README.md that only python 2 is supported and other restrictions that you guys think are relevant. Thanks again and hope the input is valuable.

**Comment by swapnil95** [comment]
Thanks @mcarrilloco. We will look into this and update the readme accordingly
