### ISSUE TITLE
"not enough arguments for format string" error

### ISSUE THREAD

**Issue by tazmaniax** [hashedin/squealy#230]
Hi, 

This query works directly with MySQL but through squealy gets the error "not enough arguments for format string" and I suspect it's because of the use of '%' in the format_date function call is causing problem for jinjasql. Is there a way to tell jinjasql to ignore the '%' ?

<img width="1064" alt="screenshot 2017-06-22 12 17 51" src="https://user-images.githubusercontent.com/1079943/27431552-de04a5ac-5744-11e7-9de6-d2bc60752d63.png">

**Comment by devashishsharma2302** [comment]
Hi chris,
Yes you're correct. This issue is due to the '%' character that is reserved for python formatting. 

**Solution -** Use **'%%'** instead of '%'.
So, your query would be -> **select DATE_FORMAT(createTimestamp, '%%Y-%%m') AS ....**

Hope this solves your issue. Thanks.

**Comment by tazmaniax** [comment]
Yes that worked, thx!
